version: "3"
services:
  node:
    build: .
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT-8080
  postgres:
    build: ./database/
    ports: 
      - "5000:5000"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}